"""
Advanced Signal Generation Engine (v2.0)
=========================================
Professional multi-strategy confluence logic for XAU/USD.

Five complementary strategies run in parallel:

  Strategy 1 — TREND MOMENTUM (primary)
    EMA alignment + price pulls back to EMA50 + RSI in momentum zone + MACD hist positive/rising.

  Strategy 2 — BREAKOUT / MOMENTUM
    Close breaks 20-bar high/low + ATR expanding + RSI confirming + MACD positive.

  Strategy 3 — RSI MEAN REVERSION (tightened 35/65 thresholds)
    RSI turning from oversold/overbought + MACD histogram flip + EMA200 trend.

  Strategy 4 — VWAP & VOLUME MOMENTUM (Institutional)
    Price cross above/below VWAP + high relative volume (>1.2x avg) + MACD direction.

  Strategy 5 — MARKET STRUCTURE & ICHIMOKU CONFLUENCE
    Uptrend/downtrend market structure (HH/HL or LH/LL) + price above/below Ichimoku Cloud + RSI.

Confidence Boosters:
  +0.08 — Active London/NY session
  +0.07 — RSI Divergence detected in direction
  +0.06 — Stochastic confirms direction
  +0.05 — Candle body ratio > 0.5 (strong directional close)
  +0.05 — EMA20 aligns with trade direction

Filters:
  - ADX Trend Strength Filter: ADX must be >= ADX_MIN_TREND_STRENGTH (default 20)
  - MTF Filter Check: Multi-timeframe trend alignment (H1/H4)
  - Min Signal Confidence: 0.65 (raised from 0.55 for higher quality)

Ref: Blueprint Section 5 (extended v2)
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

log = logging.getLogger("gold_bot.signals")


@dataclass
class Signal:
    """Represents a trading signal generated by the multi-strategy confluence engine."""
    direction:    str    # "LONG", "SHORT", or "FLAT"
    confidence:   float  # 0.0 – 1.0
    reason:       str    # Human-readable explanation
    strategy:     str    = "none"   # Which strategy fired
    timestamp:    str    = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    votes_detail: dict   = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def _safe(df: pd.DataFrame, col: str, row: int = -1):
    """Return df[col].iloc[row] or None if missing/NaN."""
    if col not in df.columns:
        return None
    val = df[col].iloc[row]
    return None if pd.isna(val) else val


# ---------------------------------------------------------------------------
# Strategy 1 — Trend Momentum (EMA alignment + pullback to EMA50)
# ---------------------------------------------------------------------------

def _strategy_trend_momentum(last, prev) -> tuple[str, float, dict]:
    """
    Logic:
      LONG  — EMA50 > EMA200 (uptrend) AND price near/below EMA50 (pullback)
              AND RSI 45-70 (momentum zone, not overbought)
              AND MACD histogram positive AND rising

      SHORT — EMA50 < EMA200 (downtrend) AND price near/above EMA50 (pullback)
              AND RSI 30-55 (momentum zone, not oversold)
              AND MACD histogram negative AND falling
    """
    result = {"strategy": "trend_momentum", "votes": {}}

    ema50  = last.get("ema50")
    ema200 = last.get("ema200")
    close  = last.get("close")
    rsi    = last.get("rsi14")
    mh     = last.get("macd_hist")
    mhs    = last.get("macd_hist_slope")

    if any(v is None for v in [ema50, ema200, close, rsi, mh, mhs]):
        return "FLAT", 0.0, result

    trend_up   = ema50 > ema200
    trend_down = ema50 < ema200

    ema50_distance_pct = (close - ema50) / ema50
    near_ema50_long  = -0.003 <= ema50_distance_pct <= 0.005
    near_ema50_short = -0.005 <= ema50_distance_pct <= 0.003

    long_votes = {
        "uptrend_ema50_gt_ema200":    trend_up,
        "pullback_to_ema50":          near_ema50_long,
        "rsi_momentum_zone":          45 <= rsi <= 70,
        "macd_hist_positive":         mh > 0,
        "macd_hist_rising":           mhs > 0,
    }

    short_votes = {
        "downtrend_ema50_lt_ema200":  trend_down,
        "pullback_to_ema50":          near_ema50_short,
        "rsi_momentum_zone":          30 <= rsi <= 55,
        "macd_hist_negative":         mh < 0,
        "macd_hist_falling":          mhs < 0,
    }

    long_count  = sum(long_votes.values())
    short_count = sum(short_votes.values())

    if long_count >= 4 and long_count > short_count:
        conf = long_count / 5.0
        result["votes"] = long_votes
        return "LONG", conf, result

    if short_count >= 4 and short_count > long_count:
        conf = short_count / 5.0
        result["votes"] = short_votes
        return "SHORT", conf, result

    return "FLAT", 0.0, {**result, "votes": {"long": long_votes, "short": short_votes}}


# ---------------------------------------------------------------------------
# Strategy 2 — Breakout / Momentum
# ---------------------------------------------------------------------------

def _strategy_breakout(last, prev) -> tuple[str, float, dict]:
    """
    Logic:
      LONG  — Close breaks above rolling 20-bar high + RSI > 52 + MACD hist > 0 + ATR expanding
      SHORT — Close breaks below rolling 20-bar low + RSI < 48 + MACD hist < 0 + ATR expanding
    """
    result = {"strategy": "breakout", "votes": {}}

    close     = last.get("close")
    rh20      = last.get("roll_high20")
    rl20      = last.get("roll_low20")
    rsi       = last.get("rsi14")
    mh        = last.get("macd_hist")
    atr       = last.get("atr14")
    atr_prev  = prev.get("atr14")

    if any(v is None for v in [close, rh20, rl20, rsi, mh, atr, atr_prev]):
        return "FLAT", 0.0, result

    atr_expanding = atr > atr_prev * 0.98

    long_votes = {
        "price_breaks_20bar_high":  close > rh20,
        "rsi_confirming_bullish":   rsi > 52,
        "macd_hist_positive":       mh > 0,
        "atr_expanding":            atr_expanding,
    }

    short_votes = {
        "price_breaks_20bar_low":   close < rl20,
        "rsi_confirming_bearish":   rsi < 48,
        "macd_hist_negative":       mh < 0,
        "atr_expanding":            atr_expanding,
    }

    long_count  = sum(long_votes.values())
    short_count = sum(short_votes.values())

    if long_count >= 4 and long_count > short_count:
        conf = long_count / 4.0
        result["votes"] = long_votes
        return "LONG", conf, result

    if short_count >= 4 and short_count > long_count:
        conf = short_count / 4.0
        result["votes"] = short_votes
        return "SHORT", conf, result

    return "FLAT", 0.0, {**result, "votes": {"long": long_votes, "short": short_votes}}


# ---------------------------------------------------------------------------
# Strategy 3 — RSI Mean Reversion (tightened thresholds)
# ---------------------------------------------------------------------------

def _strategy_rsi_reversal(last, prev) -> tuple[str, float, dict]:
    """
    Logic:
      LONG  — EMA200 trend is up + RSI < 35 & turning up + MACD hist bullish cross
      SHORT — EMA200 trend is down + RSI > 65 & turning down + MACD hist bearish cross
    """
    from config.settings import RSI_OVERSOLD, RSI_OVERBOUGHT

    result = {"strategy": "rsi_reversal", "votes": {}}

    close    = last.get("close")
    ema200   = last.get("ema200")
    rsi      = last.get("rsi14")
    rsi_prev = prev.get("rsi14")
    mh       = last.get("macd_hist")
    mh_prev  = prev.get("macd_hist")

    if any(v is None for v in [close, ema200, rsi, rsi_prev, mh, mh_prev]):
        return "FLAT", 0.0, result

    long_votes = {
        "price_above_ema200":         close > ema200,
        "rsi_oversold":               rsi < RSI_OVERSOLD,
        "rsi_turning_up":             rsi > rsi_prev,
        "macd_hist_bullish_cross":    mh > 0 and mh_prev <= 0,
    }

    short_votes = {
        "price_below_ema200":         close < ema200,
        "rsi_overbought":             rsi > RSI_OVERBOUGHT,
        "rsi_turning_down":           rsi < rsi_prev,
        "macd_hist_bearish_cross":    mh < 0 and mh_prev >= 0,
    }

    long_count  = sum(long_votes.values())
    short_count = sum(short_votes.values())

    if long_count >= 3 and long_count > short_count:
        conf = long_count / 4.0
        result["votes"] = long_votes
        return "LONG", conf, result

    if short_count >= 3 and short_count > long_count:
        conf = short_count / 4.0
        result["votes"] = short_votes
        return "SHORT", conf, result

    return "FLAT", 0.0, {**result, "votes": {"long": long_votes, "short": short_votes}}


# ---------------------------------------------------------------------------
# Strategy 4 — VWAP & Volume Momentum (NEW)
# ---------------------------------------------------------------------------

def _strategy_vwap_momentum(last, prev) -> tuple[str, float, dict]:
    """
    Logic (Institutional Order Flow):
      LONG  — Price above VWAP + Volume > 1.2x avg + MACD hist > 0 + Close > Open
      SHORT — Price below VWAP + Volume > 1.2x avg + MACD hist < 0 + Close < Open
    """
    result = {"strategy": "vwap_momentum", "votes": {}}

    close     = last.get("close")
    open_     = last.get("open")
    vwap      = last.get("vwap")
    vol_ratio = last.get("volume_ratio")
    mh        = last.get("macd_hist")

    if any(v is None for v in [close, open_, vwap, vol_ratio, mh]):
        return "FLAT", 0.0, result

    long_votes = {
        "price_above_vwap":      close > vwap,
        "high_volume":           vol_ratio >= 1.1,
        "macd_hist_positive":    mh > 0,
        "bullish_candle":        close > open_,
    }

    short_votes = {
        "price_below_vwap":      close < vwap,
        "high_volume":           vol_ratio >= 1.1,
        "macd_hist_negative":    mh < 0,
        "bearish_candle":        close < open_,
    }

    long_count  = sum(long_votes.values())
    short_count = sum(short_votes.values())

    if long_count >= 4 and long_count > short_count:
        result["votes"] = long_votes
        return "LONG", 0.80, result

    if short_count >= 4 and short_count > long_count:
        result["votes"] = short_votes
        return "SHORT", 0.80, result

    return "FLAT", 0.0, {**result, "votes": {"long": long_votes, "short": short_votes}}


# ---------------------------------------------------------------------------
# Strategy 5 — Market Structure & Ichimoku Confluence (NEW)
# ---------------------------------------------------------------------------

def _strategy_structure_ichimoku(last, prev) -> tuple[str, float, dict]:
    """
    Logic:
      LONG  — Market structure == 1 (Uptrend) + Price above Ichimoku Cloud (ichi_signal == 1) + RSI 50-70
      SHORT — Market structure == -1 (Downtrend) + Price below Ichimoku Cloud (ichi_signal == -1) + RSI 30-50
    """
    result = {"strategy": "structure_ichimoku", "votes": {}}

    struct  = last.get("market_structure")
    ichi    = last.get("ichi_signal")
    rsi     = last.get("rsi14")
    tenkan  = last.get("ichi_tenkan")
    kijun   = last.get("ichi_kijun")

    if any(v is None for v in [struct, ichi, rsi, tenkan, kijun]):
        return "FLAT", 0.0, result

    long_votes = {
        "uptrend_structure":     struct == 1,
        "above_ichimoku_cloud":  ichi == 1,
        "rsi_bullish_zone":      50 <= rsi <= 70,
        "tenkan_above_kijun":    tenkan >= kijun,
    }

    short_votes = {
        "downtrend_structure":   struct == -1,
        "below_ichimoku_cloud":  ichi == -1,
        "rsi_bearish_zone":      30 <= rsi <= 50,
        "tenkan_below_kijun":    tenkan <= kijun,
    }

    long_count  = sum(long_votes.values())
    short_count = sum(short_votes.values())

    if long_count >= 3 and long_count > short_count:
        result["votes"] = long_votes
        return "LONG", 0.75, result

    if short_count >= 3 and short_count > short_count:
        result["votes"] = short_votes
        return "SHORT", 0.75, result

    return "FLAT", 0.0, {**result, "votes": {"long": long_votes, "short": short_votes}}


# ---------------------------------------------------------------------------
# Confidence Boosters
# ---------------------------------------------------------------------------

def _apply_confidence_boosters(
    direction: str,
    base_conf: float,
    last: dict,
    prev: dict
) -> tuple[float, list]:
    """
    Adds up to ~0.30 confidence based on additional confirming factors.
    """
    bonuses = []

    # Booster 1: Active trading session (+0.08)
    if last.get("in_session") == 1:
        base_conf += 0.08
        bonuses.append("active_session(+0.08)")

    # Booster 2: RSI Divergence (+0.07)
    if direction == "LONG" and last.get("rsi_bull_div") == 1:
        base_conf += 0.07
        bonuses.append("rsi_bull_div(+0.07)")
    elif direction == "SHORT" and last.get("rsi_bear_div") == 1:
        base_conf += 0.07
        bonuses.append("rsi_bear_div(+0.07)")

    # Booster 3: Stochastic agrees with direction (+0.06)
    stoch_k = last.get("stoch_k")
    stoch_d = last.get("stoch_d")
    if stoch_k is not None and stoch_d is not None:
        if direction == "LONG" and stoch_k > stoch_d and stoch_k < 80:
            base_conf += 0.06
            bonuses.append("stoch_bull(+0.06)")
        elif direction == "SHORT" and stoch_k < stoch_d and stoch_k > 20:
            base_conf += 0.06
            bonuses.append("stoch_bear(+0.06)")

    # Booster 4: Strong directional candle body (+0.05)
    body_ratio = last.get("body_ratio")
    close = last.get("close")
    open_ = last.get("open")
    if body_ratio is not None and close is not None and open_ is not None:
        if body_ratio > 0.5:
            candle_bullish = close > open_
            if (direction == "LONG" and candle_bullish) or (direction == "SHORT" and not candle_bullish):
                base_conf += 0.05
                bonuses.append(f"strong_candle(+0.05, ratio={body_ratio:.2f})")

    # Booster 5: EMA20 short-term alignment (+0.05)
    ema20 = last.get("ema20")
    ema50 = last.get("ema50")
    if ema20 is not None and ema50 is not None:
        if direction == "LONG" and ema20 > ema50:
            base_conf += 0.05
            bonuses.append("ema20_bull(+0.05)")
        elif direction == "SHORT" and ema20 < ema50:
            base_conf += 0.05
            bonuses.append("ema20_bear(+0.05)")

    return min(base_conf, 1.0), bonuses


# ---------------------------------------------------------------------------
# Main Signal Generator
# ---------------------------------------------------------------------------

def generate_signal(df: pd.DataFrame, ml_model=None) -> Signal:
    """
    Runs all five strategies and selects the highest-confidence signal.
    Applies ADX filter, MTF check, confidence boosters, and gates against MIN_SIGNAL_CONFIDENCE.

    Args:
        df:       DataFrame with computed indicators.
        ml_model: Optional ML model.

    Returns:
        Signal object.
    """
    from config.settings import MIN_SIGNAL_CONFIDENCE, ADX_MIN_TREND_STRENGTH, SYMBOL

    if len(df) < 25:
        return Signal("FLAT", 0.0, "Insufficient data", strategy="none")

    last = {c: _safe(df, c, -1) for c in df.columns}
    prev = {c: _safe(df, c, -2) for c in df.columns}

    required = ["close", "ema50", "ema200", "rsi14", "macd_hist", "atr14"]
    for col in required:
        if last.get(col) is None:
            return Signal("FLAT", 0.0, f"Missing indicator: {col}", strategy="none")

    # -------------------------------------------------------------------
    # Filter 1: ADX Trend Strength Filter
    # -------------------------------------------------------------------
    adx_val = last.get("adx", 0.0) or 0.0
    if adx_val < ADX_MIN_TREND_STRENGTH:
        log.debug("Signal suppressed | ADX %.1f < min %.1f (ranging market)",
                  adx_val, ADX_MIN_TREND_STRENGTH)
        return Signal(
            direction="FLAT",
            confidence=round(adx_val / 100.0, 4),
            reason=f"ADX low ({adx_val:.1f} < {ADX_MIN_TREND_STRENGTH}) — market is choppy",
            strategy="none"
        )

    # -------------------------------------------------------------------
    # Run all five strategies
    # -------------------------------------------------------------------
    strategies = [
        _strategy_trend_momentum(last, prev),
        _strategy_breakout(last, prev),
        _strategy_rsi_reversal(last, prev),
        _strategy_vwap_momentum(last, prev),
        _strategy_structure_ichimoku(last, prev),
    ]

    active = [(d, c, meta) for d, c, meta in strategies if d != "FLAT"]

    if not active:
        best_conf = max(c for _, c, _ in strategies)
        return Signal(
            direction="FLAT",
            confidence=round(best_conf, 4),
            reason="No strategy reached threshold",
            strategy="none",
            votes_detail={"strategies": [m.get("strategy", "?") for _, _, m in strategies]},
        )

    # Pick the highest confidence signal among active strategies
    direction, base_conf, meta = max(active, key=lambda x: x[1])

    # -------------------------------------------------------------------
    # Filter 2: MTF Check Integration
    # -------------------------------------------------------------------
    try:
        from core.mtf_filter import check_mtf_alignment
        mtf_ok, mtf_reason = check_mtf_alignment(SYMBOL, direction)
        if not mtf_ok:
            return Signal(
                direction="FLAT",
                confidence=round(base_conf, 4),
                reason=mtf_reason,
                strategy=meta.get("strategy", "unknown")
            )
    except Exception as e:
        log.warning("MTF check failed in signal generator: %s", e)

    # -------------------------------------------------------------------
    # Optional ML layer (blends 40% ML, 60% rule)
    # -------------------------------------------------------------------
    if ml_model is not None:
        try:
            from ml.features import extract_feature_vector
            features = extract_feature_vector(df)
            ml_prob_up = ml_model.predict_proba([features])[0][1]
            blended = 0.6 * base_conf + 0.4 * ml_prob_up
            log.debug("ML blend | rule=%.3f, ml=%.3f, blended=%.3f", base_conf, ml_prob_up, blended)
            base_conf = blended
        except Exception as e:
            log.warning("ML prediction failed, using rule-only: %s", e)

    # -------------------------------------------------------------------
    # Apply confidence boosters
    # -------------------------------------------------------------------
    final_conf, bonuses = _apply_confidence_boosters(direction, base_conf, last, prev)

    # -------------------------------------------------------------------
    # Gate against minimum confidence (0.65)
    # -------------------------------------------------------------------
    strategy_name = meta.get("strategy", "unknown")

    if final_conf < MIN_SIGNAL_CONFIDENCE:
        log.debug(
            "Signal suppressed | Dir: %s | Conf: %.3f < min %.3f | Strategy: %s | Bonuses: %s",
            direction, final_conf, MIN_SIGNAL_CONFIDENCE, strategy_name, bonuses
        )
        return Signal(
            direction="FLAT",
            confidence=round(final_conf, 4),
            reason=f"{strategy_name} signal below min confidence ({final_conf:.2f} < {MIN_SIGNAL_CONFIDENCE})",
            strategy=strategy_name,
            votes_detail=meta.get("votes", {}),
        )

    bonus_str = " | ".join(bonuses) if bonuses else "none"
    reason = f"{strategy_name} | conf={final_conf:.2f} | boosters=[{bonus_str}]"

    icon = "📈" if direction == "LONG" else "📉"
    log.info(
        "%s %s signal | Strategy: %s | Confidence: %.3f | ADX: %.1f | "
        "RSI: %.1f | MACD-H: %.4f | ATR: %.2f | VWAP: %.2f",
        icon, direction, strategy_name, final_conf, adx_val,
        last.get("rsi14") or 0,
        last.get("macd_hist") or 0,
        last.get("atr14") or 0,
        last.get("vwap") or 0,
    )
    if bonuses:
        log.info("   Confidence boosters: %s", bonus_str)

    return Signal(
        direction=direction,
        confidence=round(final_conf, 4),
        reason=reason,
        strategy=strategy_name,
        votes_detail={**meta.get("votes", {}), "boosters": bonuses},
    )
